directories:
  output: RandomCanucks_Operator_Helper
  buildResources: build
appId: com.electron.randomcanucksoperatorhelper
productName: randomranucksoperatorhelper
files:
  - filter:
      - '**/*'
      - icon.ico
win:
  icon: build/icons.ico
electronVersion: 8.2.5
